### ISSUE TITLE
This knob code is not working on iphone and Ipad

### ISSUE THREAD

**Issue by mahmad2005** [andrepxx/pure-knob#4] opened 2018-09-28 01:33 UTC
This knob code is not working on iphone and Ipad. Please test the code on these.

**Comment by andrepxx** [comment] 2018-10-01 13:25
Thank you for reporting this issue.

Since I do not own *iOS* devices, I currently cannot test and debug the code on these.

Therefore, I basically have two options.

1. See if I can borrow an *iOS* device from someone else, who will let me attach a debugger to it. This might happen "eventually", but I cannot predict **when** it will happen. (It might be next week, it might be next month, it might even be next year. I just don't know in advance.)

2. Since this is an open source project, see if someone else with an *iOS* device can debug the code and file a pull request. (Unfortunately, I cannot predict if and when this will happen either.)

In the meantime, perhaps you can elaborate a bit more on what "not working" means.

1. Does it mean no knob is drawn at all? If so, does it crash your entire script or does it just not draw a knob? Can you open a *JavaScript* debugger and see an error message? If so, could you post that message, including the line number in which the error occurs.

2. Does it mean a knob is drawn, but it does not respond to events? If so, which events have you tried?

This information might help narrowing down on the issue.

I tested the knob on Linux/Firefox, Linux/Chrome, Windows/Firefox and Android/Chrome and it does work on these platforms. However, it is somehow "limited" on Android/Chrome, since unfortunately, the mobile browser has some limitations.

1. It only fires a single mouse event on "touch tap" (= left mouse button click), which is fired at **release**, which means after you lift the finger up again.

2. It fires **no events at all** on "touch down" (= mouse down), "touch drag" (= mouse move), "long tap" (= right mouse button click) and two-finger scrolling (= mouse wheel).

3. It doesn't fire an event on "double tap" (= mouse double click) either.

Therefore ...

1. You cannot "touch and pull the knob around", as you can do it on the desktop. (Android does not fire mouse or touch move event.)

2. You cannot change the value by scrolling. (Android does not fire mouse scroll event.)

3. You have no way to enable keyboard entry. (Android does not fire click events for the middle and right mouse buttons and it does not fire double click event on double tap.)

I see no actual way around these limitations. The events just seem to be unimplemented on Android. Only a single event seems to be implemented and this is mouse click / touch release, which is obviously **very** limiting.

Apart from these limitations (which, unfortunately, are limitations of the **platform**), the knob "works" on Android/Chrome.

**Comment by antdow** [comment] 2018-11-02 11:20
Not sure this should be described as having touch support when it doesn't work on mobile platforms. Even the demo page (https://www.cssscript.com/demo/canvas-javascript-knob-dial-component/) doesn't react to touch events on iPad.

**Comment by andrepxx** [comment] 2018-11-02 12:29
Well, technically it **has** touch support, since it registers event handlers for `touchstart`, `touchmove`, `touchend` and `touchcancel` events. Whether or not the mobile browser / platform actually implements and **fires** these (W3C standard) events (invokes the event handlers which we registered) is out of our control.

Also, *jQuery-Knob* (which is deprecated and we intend to replace it with this control) is described as having touch support as well, even though it is much more limited / broken than this control.

Also keep in mind that touch support "works" (though severely limited) on *Android*, which is a mobile platform. (That *Android* seemingly only fires a single event at touch release is a limitation of the platform, which is out of our control.)

Next, we are working on improving support for different platforms. However, you're a bit out of luck on *iOS*, since the developers have no access to *iOS* devices for development and testing. If you own an *iOS* device and can attach a debugger to it, feel free to contribute though. This is an open source project. Don't expect a lot of progress on this issue if no *iOS* user is willing to contribute.

Last but not least, the demo page you mention is a third-party site that was/is neither set up nor operated by us. We do provide a demo page in our repository, which you can host on your own web server for testing.

**Comment by antdow** [comment] 2018-11-02 13:25
Thanks Andre for your response.  Sadly, like yourself, my time is too limited to put in a great deal of time supporting this project however I really do appreciate your efforts and certainly for standard desktop web sites, your control is amazingly functional.

For reference, Anthony Terrien's jqKnob (whilst you state is deprecated) still works flawlessly on iOS touch devices, including the demo at http://anthonyterrien.com/demo/knob however I always like to keep my eye out for other up and coming utilities that could be of use.

Thanks again and I wish you well.

**Comment by andrepxx** [comment] 2018-11-02 13:36
I'll see if I can improve event support on *Android*. Perhaps that will fix it on *iOS* too. Since I do this in my spare time, I can't provide ETAs though. Please stand by.

Rest assured that I have a huge interest in getting this fixed as well, since I use this control in the UI of a (currently unpublished) large application.

**Comment by andrepxx** [comment] 2018-11-02 14:38
@antdow I just pushed changes to master.

Could you please test them on your *iOS* device?

At least, on *Android*, you can now change value smoothly by dragging your finger over the control.

However, there is still no way to enable numeric entry of value via (on-screen) keyboard on these devices, like we have it on the PC via double or middle click.

**Comment by andrepxx** [comment] 2018-11-05 12:54
As of now, double-tapping the control (two single-finger taps on the same control within an interval of half a second will register as a double tap) will display a numeric on-screen keyboard to allow precise entry of value.

As before, this is only tested on *Android*, not on *iOS*, but will probably work there as well.

So now, we basically offer the same functionality on touch-screen devices as we do on the desktop with mouse and keyboard.

Please report back, whether the functionality works on *iOS* as well. If it does, I think we can close this issue.

**Comment by miikaluolajanmikkola** [comment] 2019-07-05 18:09
Looking at line 955: "var touches = e.touches" - considering that this is a touchend event, it must be that e.touches.length is 0. I would try using e.changedTouches[0], which has the last touch stored after finger is lifted off the screen.

**Comment by andrepxx** [comment] 2019-07-07 08:38
Should be fixed with the latest commit.

I don't actually need the last touch point. I just need to know that the last finger has been lifted up, so I just check that indeed `touches.length === 0` and then I commit the value (and notify listeners that the value has changed).

Thank you!

**Comment by andrepxx** [comment] 2019-10-25 06:59
I think the issue is resolved.

**Closed as completed by andrepxx** 2019-10-25 06:59 UTC
Labels: bug, help wanted

**Comment by ebrensi** [comment] 2020-03-16 21:47
btw I'm not sure if you will see this message since the issue is closed but for iOS support, what I think you mean is WebKit driven browsers, which include Safari.  I have found for example that Chrome on iOS works just like Chrome anywhere else.  The Midori browser that comes stock with Manjaro XFCE (Arch-based) Linux is a WebKit browser, so you can often get an idea of what iOS users are seeing if you use it.

**Comment by andrepxx** [comment] 2020-03-17 11:35
I think the issue was with support for the touch API, which is specific for mobile devices. The first implementation did not get this to work across platforms. (It might be worth changing to the new Pointer API at some point, but this is currently not a priority.) So it was not really a browser compatibility issue. It was more of a platform compatibility issue.

The issue should be fixed / resolved in the meantime. It's just that I don't have an iOS device to verify if it works on iOS as well, which is where this issue was initially reported / recognized. However, I found that, before the change, it didn't work correctly on Android either, actually. Therefore, I fixed it for Android (where I have a device to test with) and then suspected / hoped that this would fix it for iOS too. It's just that I cannot be sure, since I don't have an iOS device to test this and never got feedback from an iOS user on this topic.
